name: " using GitHub Action for Terraform Auto CI/CD"
on:
  pull_request:
    branches:
      - remote_stats
  push:
    branches:
      - remote_stats
env:
  tf_version: "latest"
  tf_working_dir: "./src/model/"
  terraform_rg: "Web_Test_TF_RG"
  storage_account: "cnbatestorestatefile003"
  storage_account_container: "terraform-state"
  keyvault: "cnbateblogweb"
  keyvault_sc: "terraform-stste-storage-key"
jobs:
  storageaccount_create:
    name: "Azure CLI Action   "
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            # create azure resource group
            az group create --location eastasia --name ${{ env.terraform_rg }}

            # create azure storage account
            az storage account create --name ${{ env.storage_account }} --resource-group ${{ env.terraform_rg }} --location eastasia --sku Standard_LRS

            # create storage account container for tf state 
            az storage container create --name ${{ env.storage_account_container }} --account-name ${{ env.storage_account }}

            # query storage key and set variable
            ACCOUNT_KEY=$(az storage account keys list --resource-group ${{env.terraform_rg}} --account-name ${{ env.storage_account }} --query "[?keyName == 'key1'][value]" --output tsv)

            # create azure keyvault
            az keyvault create --name ${{ env.keyvault }} --resource-group ${{ env.terraform_rg }} --location eastasia --enable-soft-delete false

            # set keyvault secret,secret value is ACCOUNT_KEY
            az keyvault secret set --name ${{ env.keyvault_sc }} --vault-name ${{ env.keyvault }}  --value $ACCOUNT_KEY

  terraform_init:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init -backend-config="storage_account_name=${{ env.storage_account }}" -backend-config="container_name=${{ env.storage_account_container }}" -backend-config="access_key=${{ env.keyvault_sc }}" -backend-config="key=${{ env.keyvault_sc }}"'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform_plan:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
